export const input_list = [
    'RSA',
    'ECDHE',
    'DHE',
    'AES',
    'Camellia',
    'DES',
    'Triple DES',
    'CAST',
    'IDEA',
    'RC2',
    'RC4',
    'RC5',
    'Serpent',
    'SAFER',
    'ChaCha20',
    'Salsa20',
    'GMAC',
    'MD',
    'RIPEMD',
    'SHA',
    'BLAKE2b',
    'BLAKE2s',
    'SHAKE',
    'Kyber',
    'Dilithium',
    'Falcon',
    'SPHINICS+ SHA 256',
  "secp112r1",
  "secp128r1",
  "secp192r1",
  "secp224r1",
  "secp256r1",
  "secp384r1",
  "secp521r1",
  "x25519",
  "ffdhe2048",
  "ffdhe3072",
  "ffdhe4096",
  "ffdhe6144",
  "ffdhe8192",
  "DES",
  "Triple DES",
  "CAST5",
  "CAST6",
  "IDEA128",
  "RC2",
  "RC4",
  "RC5",
  "Serpent",
  "SAFER-K64",
  "SAFER-K128",
  "SAFER-K256",
  "ChaCha20",
  "Salsa20",
  "GMAC 128",
  "MD2",
  "MD4",
  "MD5",
  "RIPEMD-128",
  "RIPEMD-160",
  "SHA",
  "SHA-1",
  "SHA-224",
  "SHA-256",
  "SHA-384",
  "SHA-512",
  "SHA3-224",
  "SHA3-256",
  "SHA3-384",
  "SHA3-512",
  "BLAKE2b-160",
  "BLAKE2b-256",
  "BLAKE2b-384",
  "BLAKE2b-512",
  "BLAKE2s-128",
  "BLAKE2s-160",
  "BLAKE2s-224",
  "BLAKE2s-256",
  "SHAKE128",
  "SHAKE256",
  "Kyber512",
  "Kyber768",
  "Kyber1024",
  "Dilithium 2",
  "Dilithium 3",
  "Dilithium 5",
  "Falcon 512",
  "Falcon 1024",
  'ECB',
  'CBC',
  'CFB',
  'OFB',
  'CTR',
  'GCM',
  'CCM',
  'DiffieHellman',

  
]
//     "fernet",
//     "Fernet",
//     "MultiFernet",
//     "hashes",
//     "PBKDF2HMAC",
//     "rsa",
//     "x509",
//     "SHA256",
//     "shake_128",
//     "ChaCha20Poly1305",
//     "AESGCM",
//     "AESOCB3",
//     "AESSIV",
//     "AESCCM",
//     "Ed25519PrivateKey",
//     "ed25519",
//     "X25519PrivateKey",
//     "HKDF",
//     "x25519",
//     "Ed448PrivateKey",
//     "X448PrivateKey",
//     "x448",
//     "dsa",
//     "SSHCertificateType",
//     "SSHCertificateBuilder",
//     "Scrypt",
//     "ConcatKDFHash",
//     "ConcatKDFHMAC",
//     "HKDFExpand",
//     "CounterLocation",
//     "KBKDFHMAC",
//     "X963KDF",
//     "cmac",
//     "HOTP",
//     "SHA1",
//     "TOTP",
//     "hashlib",
//     "hexlify",
//     "defaultdict",
//     "SECP256k1",
//     "SigningKey",
//     "cryptography_vectors",
//     "cryptography",
//     "Salsa20",
//     "AES",
//     "get_random_bytes",
//     "b64encode",
//     "get_random_bytes",
//     "unpad",
//     "SHA256",
//     "SHA224",
//     "SHA384",
//     "SHA512",
//     "SHA3_224",
//     "SHA3_256",
//     "SHA3_384",
//     "SHA3_512",
//     "BLAKE2s",
//     "BLAKE2b",
//     "TupleHash128",
//     "TupleHash256",
//     "SHAKE128",
//     "SHAKE256",
//     "CMAC",
//     "Poly1305",
//     "KMAC128",
//     "KMAC256",
//     "SHA1",
//     "MD2",
//     "MD5",
//     "RIPEMD160",
//     "keccak",
//     "DSA",
//     "DSS",
//     "ECC",
//     "PBKDF2",
//     "scrypt",
//     "bcrypt",
//     "HKDF",
//     "Shamir",
//     "unhexlify",
//     "key_to_english",
//     "DerInteger",
//     "DerSequence",
//     "DerObjectId",
//     "DerBitString",
//     "DerOctetString",
//     "PKCS1_OAEP",
// ]